### ISSUE TITLE
Where is the sample DB file

### ISSUE THREAD

**Issue by tawfekk** [codemedic79/CleverCRM#2]
Hi

I can't seem to find the sample db file as described in the readme _"This is a complete project which includes a sample database file"_)

Could you please provide the file or sql code to create tables etc? 

Great project btw :-)

**Comment by codemedic79** [comment]
@tawfekk I'm sorry, I have been so busy with other things and didn't notice I had a message. Let me see if I can find that. I know I had it somewhere LOL.

**Comment by codemedic79** [comment]
@tawfekk ,
The SQL script is available.
